### ISSUE TITLE
Error training

### ISSUE THREAD

**Issue by TuTinh** [chingi071/SOLOv2_training#1]
I see this error when running cmd train. Can you help me?

> Traceback (most recent call last):
  File "tools/train.py", line 13, in <module>
    from mmdet.apis import set_random_seed, train_detector
  File "/content/drive/MyDrive/VienAI/Road-Crack-Segment/SOLO/SOLO/mmdet/apis/__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/content/drive/MyDrive/VienAI/Road-Crack-Segment/SOLO/SOLO/mmdet/apis/inference.py", line 11, in <module>
    from mmdet.core import get_classes
  File "/content/drive/MyDrive/VienAI/Road-Crack-Segment/SOLO/SOLO/mmdet/core/__init__.py", line 6, in <module>
    from .post_processing import *  # noqa: F401, F403
  File "/content/drive/MyDrive/VienAI/Road-Crack-Segment/SOLO/SOLO/mmdet/core/post_processing/__init__.py", line 1, in <module>
    from .bbox_nms import multiclass_nms
  File "/content/drive/MyDrive/VienAI/Road-Crack-Segment/SOLO/SOLO/mmdet/core/post_processing/bbox_nms.py", line 3, in <module>
    from mmdet.ops.nms import nms_wrapper
  File "/content/drive/MyDrive/VienAI/Road-Crack-Segment/SOLO/SOLO/mmdet/ops/__init__.py", line 2, in <module>
    from .dcn import (DeformConv, DeformConvPack, DeformRoIPooling,
  File "/content/drive/MyDrive/VienAI/Road-Crack-Segment/SOLO/SOLO/mmdet/ops/dcn/__init__.py", line 1, in <module>
    from .deform_conv import (DeformConv, DeformConvPack, ModulatedDeformConv,
  File "/content/drive/MyDrive/VienAI/Road-Crack-Segment/SOLO/SOLO/mmdet/ops/dcn/deform_conv.py", line 10, in <module>
    from . import deform_conv_cuda
ImportError: /content/drive/MyDrive/VienAI/Road-Crack-Segment/SOLO/SOLO/mmdet/ops/dcn/deform_conv_cuda.cpython-37m-x86_64-linux-gnu.so: undefined symbol: THPVariableClass

![image](https://user-images.githubusercontent.com/53398102/160975204-5bc90680-a281-4764-b29d-819b1a4f61a4.png)

**Comment by chingi071** [comment]
You can check torch, torchvision version. Or you can create the new environment and install torch, torchvision.
`conda create --name <environment_name> python=3.7 -y`
Pytorch install reference: https://pytorch.org/get-started/locally/
My version is CUDA 10.2, cuDNN 7.6.5, python 3.7.9, torch 1.9.0, torchvision 0.10.0.

**Comment by TuTinh** [comment]
Very helpful, I followed you and then got this error. Can you help me?

> /usr/local/lib/python3.7/dist-packages/mmdet/models/builder.py:53: UserWarning: train_cfg and test_cfg is deprecated, please specify them in model
  'please specify them in model', UserWarning)
Traceback (most recent call last):
  File "tools/train.py", line 125, in <module>
    main()
  File "tools/train.py", line 101, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/usr/local/lib/python3.7/dist-packages/mmdet/models/builder.py", line 59, in build_detector
    cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/usr/local/lib/python3.7/dist-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/utils/registry.py", line 45, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'SOLOv2 is not in the models registry'

![image](https://user-images.githubusercontent.com/53398102/162106997-a5114c47-17e1-44f6-9aad-54f85df98ddf.png)

**Comment by chingi071** [comment]
Did you change configs/solov2/solov2_light_448_r18_fpn_8gpu_3x.py ?
You can refer to this article. 
https://medium.com/ching-i/solov2-%E8%A8%93%E7%B7%B4%E6%95%99%E5%AD%B8-90591960b5c7
